[Launcher]
always_on_top = true
x = 94
y = 48

[PSX]
enabled = true
path1 = /Applications/Aerowinx.app
; Terminal command to verify this detection:
; ps -axo pid=,command= | grep -F -- "-jar Aerowinx.jar" | grep -v grep
detect1 = -jar Aerowinx.jar
path2 =
detect2 =
label = PSX
hidden1 = false
hidden2 = false

[PFPx]
enabled = true
path1 = /Applications/Aerowinx PFPx.app
detect1 =
path2 =
detect2 =
label = PFPx
hidden1 = false
hidden2 = false

[SimLink]
enabled = true
path1 = /Applications/PSX/Aerowinx Simlink
detect1 =
path2 = /Applications/Navigraph Simlink.app
detect2 =
label = SimLink
hidden1 = true
hidden2 = false

[Volanta]
enabled = true
path1 = /Applications/PSX/Aerowinx Volanta
detect1 =
path2 = /Applications/Volanta.app
detect2 =
label = Volanta
hidden1 = true
hidden2 = false

[xPilot]
enabled = true
path1 = /Applications/PSX/Aerowinx xPilot
detect1 =
path2 = /Applications/xPilot.app
detect2 =
label = xPilot
hidden1 = false
hidden2 = false

[GPS]
enabled = false
path1 = /Applications/PSX GPS Interference.app
detect1 =
path2 =
detect2 =
label = GPS
hidden1 = false
hidden2 = false
